name: rocket_apps_graph_api
description: Graph Like RESTful client apis design

publish_to: 'none'

version: 0.1.0
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rocket_apps_http:
    git:
      url: https://github.com/spaceneedl/rocket_apps_flutter.git
      ref: main
      path: src/rocket_apps_http
    
dev_dependencies:
  flutter_test:
    sdk: flutter