name: rocket_apps_widget
description: Useful widgets for the vast majority of apps

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^0.21.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
