name: rocket_apps_http
description: A helpful package to boost http request implementation

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.13.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter